apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-system-deployment
  namespace: rag-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-system
  template:
    metadata:
      labels:
        app: rag-system
    spec:
      containers: 
      - name: rag-system-container
        image: shahryar371/rag-system-image:latest
        ports:
        - containerPort: 8000    
        envFrom:
        - configMapRef:
            name: rag-system-config
        - secretRef:
            name: rag-system-secret
        volumeMounts:
        - name: chroma-db-volume
          mountPath: /data  
      volumes:
      - name: chroma-db-volume
        persistentVolumeClaim:
          claimName: chroma-db-pvc
      requests:
        memory: "2Gi"
        cpu: "500m"        